/**
 * Calibrate the experiment designer's analysis against known truth and write
 * the result to docs/calibration.json, the single source of the calibration
 * table on /methods, in docs/model-card.md and in the README.
 *
 *   cd web && pnpm calibrate           # regenerate docs/calibration.json
 *   cd web && pnpm calibrate --check   # fail if the committed file is stale
 *
 * Everything that changes a number is fixed and recorded in the output: the
 * design (583 customers per arm, baseline 35%, α = 0.05, 10-minute treatment
 * window), the seed ranges (simulation seeds 1..2000 for the +8-point row and
 * 2001..4000 for the A/A row, so the rows are independent), and the
 * fulfilment pool (minutes to ready of the
 * served orders in the committed data/seed.db, with its SHA-256). The file
 * has no timestamp, so a rerun on the same code reproduces it byte for byte.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { asc } from "drizzle-orm";
import { createDb, runMigrations } from "../src/db/connection";
import { orders } from "../src/db/schema";
import { fulfilmentMinutes } from "../src/lib/analytics/ops";
import { calibrate } from "../src/lib/experiments/calibrate";
import { DEFAULT_DESIGN, planSampleSize } from "../src/lib/experiments/design";
import {
  DEFAULT_PEEK_RUN,
  PEEKING_REPS,
  PEEKING_SEED,
  runPeeking,
} from "../src/lib/experiments/runs";

const REPS = 2000;
const FIRST_SEED = 1;
const WEB = path.resolve(import.meta.dirname, "..");
const OUT = path.resolve(WEB, "..", "docs", "calibration.json");

/** The minutes-to-ready pool the app resamples from on a fresh copy of the seed snapshot. */
async function seedPool(): Promise<number[]> {
  const tmp = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "snacks-calibrate-")), "seed.db");
  fs.copyFileSync(path.join(WEB, "data", "seed.db"), tmp);
  const { db, client } = createDb(`file:${tmp}`);
  try {
    await runMigrations(db, WEB);
    const rows = await db.select().from(orders).orderBy(asc(orders.startTime));
    const ops = rows.map((r) => ({
      orderId: r.orderId,
      vanId: r.vanId,
      status: r.status,
      startTime: r.startTime.getTime(),
      discountTime: r.discountTime.getTime(),
      fulfilledTime: r.fulfilledTime?.getTime() ?? null,
      discountApplied: r.discountApplied,
      rating: r.rating,
      fulfilmentImputed: r.fulfilmentImputed,
      closedOutAt: r.closedOutAt?.getTime() ?? null,
    }));
    // Same rounding as experimentFacts() in src/server/analytics.ts.
    return fulfilmentMinutes(ops).map((m) => Math.round(m * 100) / 100);
  } finally {
    client.close();
    fs.rmSync(path.dirname(tmp), { recursive: true, force: true });
  }
}

async function main() {
  const check = process.argv.includes("--check");
  const pool = await seedPool();
  const plan = planSampleSize(DEFAULT_DESIGN);
  if (!plan) throw new Error("the default design has no sample size");
  const base = {
    perArm: plan.perArm,
    baseline: DEFAULT_DESIGN.baseline,
    alpha: DEFAULT_DESIGN.alpha,
    treatmentWindow: DEFAULT_DESIGN.treatmentWindow,
    reps: REPS,
    pool,
  };
  const started = performance.now();
  const rows = [
    calibrate({ ...base, effect: DEFAULT_DESIGN.mde, firstSeed: FIRST_SEED }),
    calibrate({ ...base, effect: 0, firstSeed: FIRST_SEED + REPS }),
  ];
  const peeking = runPeeking(DEFAULT_PEEK_RUN);
  const output = {
    description:
      "Calibration of the /admin/experiments analysis against known truth. Generated by web/scripts/calibrate-simulation.ts (pnpm calibrate); do not edit by hand.",
    command: "cd web && pnpm calibrate",
    design: {
      perArm: plan.perArm,
      baseline: DEFAULT_DESIGN.baseline,
      plannedEffect: DEFAULT_DESIGN.mde,
      alpha: DEFAULT_DESIGN.alpha,
      plannedPower: DEFAULT_DESIGN.power,
      intervalLevel: 1 - DEFAULT_DESIGN.alpha,
      interval: "Newcombe hybrid score",
      tests: ["pooled two-proportion z-test", "exact permutation test (hypergeometric)"],
      treatmentWindowMinutes: DEFAULT_DESIGN.treatmentWindow,
    },
    seeds:
      "Each row lists its seed range: replicate r of a row uses simulation seed first + r (r = 0..reps-1). The rows use disjoint ranges, so they are independent.",
    fulfilmentPool: {
      source:
        "served orders in web/data/seed.db (housekeeping-imputed times excluded), minutes rounded to 0.01",
      size: pool.length,
      sha256: createHash("sha256").update(JSON.stringify(pool)).digest("hex"),
      values: pool,
    },
    uncertainty:
      "Shares carry Wilson 95% intervals for simulation error; the mean difference carries its Monte Carlo standard error (SD / sqrt(reps)).",
    rows,
    peeking: {
      reps: PEEKING_REPS,
      seed: PEEKING_SEED,
      looks: peeking.looks,
      perArm: peeking.perArm,
      baseline: DEFAULT_PEEK_RUN.baseline,
      alpha: peeking.alpha,
      fixedHorizon: peeking.fixedHorizon,
      stopAtFirstSignificantLook: peeking.peeking,
      pocock: peeking.pocock,
      pocockZ: peeking.pocockZ,
    },
  };
  const text = `${JSON.stringify(output, null, 2)}\n`;
  const seconds = ((performance.now() - started) / 1000).toFixed(1);
  if (check) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    if (current !== text) {
      console.error(`${path.relative(process.cwd(), OUT)} is stale: run pnpm calibrate`);
      process.exitCode = 1;
      return;
    }
    console.log(`calibration reproduced exactly (${seconds}s)`);
    return;
  }
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} in ${seconds}s`);
  for (const r of rows) {
    console.log(
      `effect ${r.injectedEffect}: coverage ${(100 * r.coverage.p).toFixed(1)}%, reject (z) ${(100 * r.rejectZ.p).toFixed(1)}%`,
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
